### ISSUE TITLE
How to do PCA analysis

### ISSUE THREAD

**Issue by facias914** [vidit09/domaingen#5] opened 2023-10-06 12:38 UTC
I read your paper and it is a very good piece of work.
I would like to ask how PCA analysis is done. Can you provide the code?

**Comment by vidit09** [comment] 2023-10-06 14:04
Hello,

Thank you for your interest in our work.

We use sklearn's PCA function to estimate the projections and use 3pcs to do so. PCA is applied to the original image embeddings and image embeddings using the opt. augmentation together.

We obtain 512-dim image embeddings with the frozen CLIP visual encoder and the same using the optimized augmentation on day images. We take up to 15 random crops per image and pass it to the visual encoder. The final 512-dim embedding of an image is the mean of the embeddings of 15 crops.

**Comment by facias914** [comment] 2023-10-07 03:24
> Hello,
> 
> Thank you for your interest in our work.
> 
> We use sklearn's PCA function to estimate the projections and use 3pcs to do so. PCA is applied to the original image embeddings and image embeddings using the opt. augmentation together.
> 
> We obtain 512-dim image embeddings with the frozen CLIP visual encoder and the same using the optimized augmentation on day images. We take up to 15 random crops per image and pass it to the visual encoder. The final 512-dim embedding of an image is the mean of the embeddings of 15 crops.

Thank You! I get the PCA result successfully

**Comment by vidit09** [comment] 2023-10-07 06:32
Closing it now

**Closed as completed** 2023-10-07 06:32 UTC

**Comment by cuttle-fish-my** [comment] 2023-11-03 15:11
> Hello,
> 
> Thank you for your interest in our work.
> 
> We use sklearn's PCA function to estimate the projections and use 3pcs to do so. PCA is applied to the original image embeddings and image embeddings using the opt. augmentation together.
> 
> We obtain 512-dim image embeddings with the frozen CLIP visual encoder and the same using the optimized augmentation on day images. We take up to 15 random crops per image and pass it to the visual encoder. The final 512-dim embedding of an image is the mean of the embeddings of 15 crops.

Hi! Thanks to this fantastic work! I'm also trying to reproduce the pca result and I got a lot problems:
1. I wonder where is the ``opt.augmentation``  in the codebase?  Are the "image embeddings using the opt. augmentation together" equivalent to ``\bar{z}_j`` in paper?
2. I tried to visualize the features (``z`` in paper) of different domain and the generated target image embedding (``z_j^*`` in paper) with pca , but I got the following weird figure:
![vis](https://github.com/vidit09/domaingen/assets/82512952/adeffdd5-b4f1-4f8d-81bb-4c31618825f4)
where the feature of target domains (fog_day, clear_night etc.) are very close to the source domain's (day), but the generated target image emeddings (e.g. day2fog_day) are far away from the corresponding target embedding. It's weird since I expect the generated target image embeddings should be more similar to the real target image embedding. I just wonder is this normal?

**Comment by fengjingchehu** [comment] 2024-09-09 12:02
> > 你好
> > 感谢您对我们的工作感兴趣。
> > 我们使用 sklearn 的 PCA 函数来估计预测并使用 3pcs 来估计。PCA 一起应用于原始图像嵌入和使用 Opt. Augmentation 的图像嵌入。
> > 我们使用冻结的 CLIP 视觉编码器获得 512 维图像嵌入，并使用日间图像的优化增强获得相同的图像嵌入。我们每张图像最多随机裁剪 15 次，并将其传递给视觉编码器。图像的最终 512 维嵌入是 15 个裁剪的嵌入的平均值。
> 
> 谢谢！我成功获得 PCA 结果

I wonder how can i 

> > Hello,
> > Thank you for your interest in our work.
> > We use sklearn's PCA function to estimate the projections and use 3pcs to do so. PCA is applied to the original image embeddings and image embeddings using the opt. augmentation together.
> > We obtain 512-dim image embeddings with the frozen CLIP visual encoder and the same using the optimized augmentation on day images. We take up to 15 random crops per image and pass it to the visual encoder. The final 512-dim embedding of an image is the mean of the embeddings of 15 crops.
> 
> Thank You! I get the PCA result successfully

I wonder how can i get such PCA result?

**Comment by vidit09** [comment] 2024-09-17 10:19
Hello,
It is as described in the text above:

> We use sklearn's PCA function to estimate the projections and use 3pcs to do so. PCA is applied to the original image embeddings and image embeddings using the opt. augmentation together.

> We obtain 512-dim image embeddings with the frozen CLIP visual encoder and the same using the optimized augmentation on day images. We take up to 15 random crops per image and pass it to the visual encoder. The final 512-dim embedding of an image is the mean of the embeddings of 15 crops.
